// Church data from: https://www.cbint.org/iglesias
export const iglesias = [
  {
    name: "CBI Barranquilla",
    location: "Colombia",
    pastors: "Prs. Rafael & Adriana Gómez ",
    address: "Sede Villa Country | Kra 59A # 77 - 35 Barranquilla",
    phone: "+57 301 285 8302",
    website: "https://www.cbint.org",
    facebook: "https://www.facebook.com/CBINacidosdeNuevo/",
    instagram: "https://www.instagram.com/cbint/",
    featured: true,
  },
  {
    name: "CBI Barcelona",
    location: "España",
    pastors: "Prs. Clemente y Betty González",
    phone: "+34 695 799237",
    facebook: "https://www.facebook.com/CBIBCN",
    instagram: "https://www.instagram.com/cbibarcelona/",
  },
  {
    name: "CBI Bucaramanga",
    location: "Colombia",
    pastors: "Pr. Salvador De La Hoz Benedetti",
    phone: "+57 316 8757837",
    facebook: "https://www.facebook.com/cbibucaramanga",
    instagram: "https://www.instagram.com/cbi.b/",
  },
  {
    name: "CBI Cartagena",
    location: "Colombia",
    pastors: "Pr. Simón Ariel Bermúdez Hernández",
    phone: "+57 5 6609190",
    facebook: "https://www.facebook.com/iglesiacentrobiblicointernacionalcartagena",
    instagram: "https://www.instagram.com/iglesiacbicartagena/",
  },
  {
    name: "CBI Cartagena Villas",
    location: "Colombia",
    pastors: "Pr. Ángel Caraballo",
    phone: "+57 321 8382701",
    facebook: "https://www.facebook.com/194717407379658/",
    instagram: "https://instagram.com/cbivillas",
  },
  {
    name: "CBI Juan de Acosta",
    location: "Colombia",
    pastors: "Pr. Carlos & Leyda Rudas",
    address: "Calle 6 No. 4-46",
    phone: "+57 304 3539143",
  },
  {
    name: "CBI Kendall",
    location: "USA",
    pastors: "Pra. Miriam Ballestas",
    facebook: "https://www.facebook.com/profile.php?id=100015163868721",
  },
  {
    name: "CBI Medellín",
    location: "Colombia",
    pastors: "Pr. Marcos Manrique Hernández",
    phone: "+57 4 5018165",
    facebook: "https://www.facebook.com/cbimedellin",
    instagram: "https://www.instagram.com/cbimedellin/",
  },
  {
    name: "CBI Miami Lakes",
    location: "USA",
    pastors: "Pr. Boris Acosta",
    phone: "+1 305 362 6917",
    website: "https://cbinternacional.com/",
    facebook: "https://www.facebook.com/cbimiamilakes",
    instagram: "https://www.instagram.com/cbimiamilakes/",
    youtube: "https://www.youtube.com/user/cbimiami",
  },
  {
    name: "CBI New Jersey",
    location: "USA",
    pastors: "Pres. Ricardo & Jackeline Rudd",
    facebook: "https://www.facebook.com/CbintNJ",
    instagram: "https://www.instagram.com/cbinj/",
  },
  {
    name: "CBI Occidente Bogotá",
    location: "Colombia",
    pastors: "Pra. Maria Emera Avellaneda de Fonseca",
    facebook: "https://www.facebook.com/emerita.avellaneda.9",
    instagram: "https://www.instagram.com/cbioccidente/",
  },
  {
    name: "CBI Puerto Colombia",
    location: "Atlántico, Colombia",
    pastors: "Pr. Miguel Ferrer",
    phone: "+57 301 257 5600",
    facebook: "https://www.facebook.com/cbi.elohim",
    instagram: "https://www.instagram.com/cbipuerto/",
  },
  {
    name: "CBI Recreo Barranquilla",
    location: "Colombia",
    pastors: "Pr. Edgar Sandoval",
    phone: "+57 301 228 1397",
    facebook: "https://www.facebook.com/cbibeitisrael",
    instagram: "https://www.instagram.com/cbibeitisrael/",
  },
  {
    name: "CBI Riohacha",
    location: "Colombia",
    pastors: "Pr. Robinson Mejía",
    facebook: "https://www.facebook.com/cbi.riohacha.3",
    instagram: "https://instagram.com/me_rcha",
  },
  {
    name: "CBI Rodadero",
    location: "Colombia",
    pastors: "Pr. Igor Muelle",
    phone: "+57 5 439 4538",
    website: "https://iglesiacbr.org/",
    facebook: "https://www.facebook.com/iglesiacbr",
    instagram: "https://www.instagram.com/iglesiacbr",
    youtube: "https://www.youtube.com/iglesiacbr",
  },
  {
    name: "CBI Santa Marta",
    location: "Colombia",
    pastors: "Pr. Ángel Custodio Flórez S.",
    facebook: "https://www.facebook.com/cbiemanuel",
    instagram: "https://www.instagram.com/cbiesantamarta/",
  },
  {
    name: "CBI Simón Bolívar",
    location: "Barranquilla, Colombia",
    pastors: "Pr. Armando R. Roca Nieto",
    phone: "+57 300 300 0577",
    facebook: "https://www.facebook.com/CBINacidosdeNuevo/",
  },
  {
    name: "CBI St. Cloud",
    location: "USA",
    pastors: "Prs. Paul & Jennifer Smit",
    phone: "+1 407 731 0206",
    facebook: "https://www.facebook.com/cbistcloud",
    instagram: "https://www.instagram.com/cbistcloud/",
  },
  {
    name: "CBI Wayuu La Paz",
    location: "Guajira, Colombia",
    pastors: "Pra. Reyes Lindao Uriana",
    phone: "+57 311 416 0141",
  },
  {
    name: "CBI Valledupar",
    location: "Colombia",
    pastors: "Pr. Clemente Meneses Escalona",
    phone: "+57 310 367 7454",
    facebook: "https://www.facebook.com/CBI.VALLEDUPAR",
    instagram: "https://www.instagram.com/cbivalledupar/",
  },
]